/your-project-root
├── netlify.toml               ✅ publish = "public"
├── public/                    ✅ contains index.html
│   └── index.html
├── netlify/
│   └── functions/
│       └── handleChat.js      ✅ backend function
